branches:
  - master
  - name: release-+([0-9]).+([0-9]).+([0-9])
    prerelease: beta
ci: true
tagFormat: ${version}
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - generateNotesCmd: sh prepare_release.sh ${nextRelease.version} ${branch.name} "${nextRelease.notes}" ${lastRelease.version} ${Date.now()}
  - - "@semantic-release/github"
    - assets:
      - path: "code4z.vsix"
        label: "code4z-${nextRelease.version}.vsix"
        name: "code4z-${nextRelease.version}.vsix"
